# Generated by Django 4.2.16 on 2024-11-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='水果名')),
                ('description', models.CharField(max_length=250, verbose_name='水果简介')),
                ('image', models.ImageField(upload_to='food/images/', verbose_name='水果海报')),
                ('url', models.URLField(blank=True, verbose_name='水果链接')),
            ],
        ),
    ]
